name: Flask CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest


      - name: Run tests
        run: pytest --html=test-report.html
    

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
         name: pytest-report
         path: test-report.html

      - name: Build Docker image
        run: |
          docker build -t flask-ci-project .